version: '3'
services:
  shb-v2-nginx:
    container_name: "shb-v2-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - shb-v2-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  shb-v2-app:
    container_name: "shb-v2-app"
    build:
      context: ./docker/php
    depends_on:
      - shb-v2-mysql
    ports:
    - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  shb-v2-mysql:
    image: mysql:8.0.28
    command: --max_allowed_packet=32505856
    container_name: "shb-v2-mysql"
    volumes:
      - ./docker/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=shb-v2
    ports:
      - 3306:3306

  shb-v2-redis:
    image: redis:alpine
    container_name: "shb-v2-redis"
    ports:
      - 16379:6379